import {
    Ambulance,
    Baby,
    Book,
    Car,
    CornerDownRight,
    CreditCard,
    CupSoda,
    DollarSign,
    Droplet,
    Dumbbell,
    Gift,
    GripVertical,
    Hammer,
    Heart,
    Home,
    Monitor,
    PawPrint,
    Percent,
    Phone,
    Plane,
    Podcast,
    Receipt,
    ShieldCheck,
    Shirt,
    ShoppingBasket,
    ShoppingCart,
    Smartphone,
    Smile,
    Star,
    Sun,
    Tag,
    TrendingUp,
    Utensils,
    Video,
    Wifi,
} from 'lucide-react';
import { AiOutlineArrowLeft, AiOutlineCheckCircle, AiOutlineFire } from 'react-icons/ai';
import { BiArrowToBottom, BiArrowToTop, BiTransfer } from 'react-icons/bi';
import { BsFillPiggyBankFill } from 'react-icons/bs';
import { FaFighterJet, FaMoneyCheckAlt } from 'react-icons/fa';
import {
    FiArrowRight,
    FiAward,
    FiBarChart2,
    FiCalendar,
    FiCheck,
    FiChevronLeft,
    FiChevronRight,
    FiChevronsDown,
    FiChevronsLeft,
    FiChevronsRight,
    FiChevronsUp,
    FiEdit3,
    FiEye,
    FiEyeOff,
    FiGrid,
    FiHome,
    FiInbox,
    FiLogOut,
    FiMenu,
    FiPieChart,
    FiPlus,
    FiRotateCcw,
    FiSave,
    FiSearch,
    FiSettings,
    FiTrash,
    FiTrash2,
} from 'react-icons/fi';
import { GiBrain, GiLaurelsTrophy, GiRunningShoe } from 'react-icons/gi';
import { HiFire } from 'react-icons/hi';
import { IoIosNotificationsOutline, IoIosTimer, IoIosTrophy, IoMdFitness } from 'react-icons/io';
import { IoCardOutline, IoCashOutline } from 'react-icons/io5';
import { MdFlashOn, MdOutlineArchive, MdSchool, MdStars, MdTimer } from 'react-icons/md';
import { RiBankLine } from 'react-icons/ri';
import { RxCross2 } from 'react-icons/rx';

export const Icons$ = {
    Inbox: FiInbox,
    Complete: FiCheck,
    Cross: RxCross2,
    ArrowTop: FiChevronsUp,
    ArrowBottom: FiChevronsDown,
    ArrowRight: FiArrowRight,
    Streak: HiFire,
    Dashboard: FiHome,
    Menu: FiMenu,
    Notifications: IoIosNotificationsOutline,
    Chart: FiPieChart,
    Add: FiPlus,
    Edit: FiEdit3,
    Delete: FiTrash,
    TrashBin: FiTrash2,
    Archive: MdOutlineArchive,
    Show: FiEye,
    Hide: FiEyeOff,
    Back: FiChevronLeft,
    Left: FiChevronLeft,
    Right: FiChevronRight,
    LeftDouble: FiChevronsLeft,
    RightDouble: FiChevronsRight,
    Grid: FiGrid,
    Save: FiSave,
    Reset: FiRotateCcw,
    Stats: FiBarChart2,
    Calendar: FiCalendar,
    Settings: FiSettings,
    Logout: FiLogOut,
    Award: FiAward,
    Trophy: GiLaurelsTrophy,
    Finance: FaMoneyCheckAlt,
    Search: FiSearch,
    DragHandle: GripVertical,
    achievements: {
        StreakStarter: AiOutlineFire,
        HabitFormed: AiOutlineCheckCircle,
        ConsistencyChampion: IoIosTrophy,
        HabitualHero: IoMdFitness,
        HabitMaster: MdSchool,
        HabitProdigy: GiBrain,
        HabitLegend: MdStars,
        SteadyEddie: IoIosTimer,
        Relentless: MdTimer,
        Unstoppable: GiRunningShoe,
        SurpassingLimits: MdFlashOn,
        Perseverance: FaFighterJet,
        ComebackKid: AiOutlineArrowLeft,
    },
    transaction_types: {
        transfer: BiTransfer,
        income: BiArrowToBottom,
        expense: BiArrowToTop,
    },

    account_types: {
        cash: IoCashOutline,
        card: IoCardOutline,
        deposit: RiBankLine,
        loan: BsFillPiggyBankFill,
    },
    categoryIcons: {
        income: {
            salary: DollarSign,
            freelance: Monitor,
            investments: TrendingUp,
            rental: Home,
            bonus: Star,
            sales: ShoppingCart,
            gifts: Gift,
            refund: CornerDownRight,
        },
        expense: {
            groceries: ShoppingBasket,
            dining: Utensils,
            home: Home,
            utilities: Droplet,
            receipt: Receipt,
            bills: CreditCard,
            taxes: Percent,
            transportation: Car,
            entertainment: Video,
            healthcare: Ambulance,
            education: Book,
            clothing: Shirt,
            insurance: ShieldCheck,
            gifts: Gift,
            electronics: Smartphone,
            travel: Plane,
            pets: PawPrint,
            car: Car,
            subscriptions: Podcast,
            beauty: Sun,
            hobbies: Star,
            charity: Heart,
            repair: Hammer,
            investments: TrendingUp,
            loan: CreditCard,
            childcare: Baby,
            party: CupSoda,
            dental: Smile,
            shopping: ShoppingCart,
            memberships: Tag,
            internet: Wifi,
            phone: Phone,
            sport: Dumbbell,
        },
    },
} as const;
