import {
    Ambulance,
    Baby,
    Book,
    Car,
    CornerDownRight,
    CreditCard,
    CupSoda,
    DollarSign,
    Droplet,
    Dumbbell,
    Gift,
    Hammer,
    Heart,
    Home,
    Monitor,
    PawPrint,
    Percent,
    Phone,
    Plane,
    Podcast,
    Receipt,
    ShieldCheck,
    Shirt,
    ShoppingBasket,
    ShoppingCart,
    Smartphone,
    Smile,
    Star,
    Sun,
    Tag,
    TrendingUp,
    Utensils,
    Video,
    Wifi,
} from 'lucide-react';
import {
    AiOutlineArrowLeft,
    AiOutlineCheckCircle,
    AiOutlineFire,
    BiArrowToBottom,
    BiArrowToTop,
    BiTransfer,
    BsFillPiggyBankFill,
    FaFighterJet,
    FaMoneyCheckAlt,
    FiAward,
    FiBarChart2,
    FiCalendar,
    FiLogOut,
    FiSearch,
    FiSettings,
    GiBrain,
    GiLaurelsTrophy,
    GiRunningShoe,
    IoCardOutline,
    IoCashOutline,
    IoIosTimer,
    IoIosTrophy,
    IoMdFitness,
    MdFlashOn,
    MdOutlineArchive,
    MdSchool,
    MdStars,
    MdTimer,
    RiBankLine,
} from 'react-icons/all';
import {
    FiArrowRight,
    FiCheck,
    FiChevronLeft,
    FiChevronRight,
    FiChevronsDown,
    FiChevronsLeft,
    FiChevronsRight,
    FiChevronsUp,
    FiEdit3,
    FiEye,
    FiEyeOff,
    FiGrid,
    FiHome,
    FiInbox,
    FiMenu,
    FiPieChart,
    FiPlus,
    FiRotateCcw,
    FiSave,
    FiTrash,
    FiTrash2,
} from 'react-icons/fi';
import { HiFire } from 'react-icons/hi';
import { IoIosNotificationsOutline } from 'react-icons/io';
import { RxCross2 } from 'react-icons/rx';

const Icons = {
    Inbox: FiInbox,
    Complete: FiCheck,
    Cross: RxCross2,
    ArrowTop: FiChevronsUp,
    ArrowBottom: FiChevronsDown,
    ArrowRight: FiArrowRight,
    Streak: HiFire,
    Dashboard: FiHome,
    Menu: FiMenu,
    Notifications: IoIosNotificationsOutline,
    Chart: FiPieChart,
    Add: FiPlus,
    Edit: FiEdit3,
    Delete: FiTrash,
    TrashBin: FiTrash2,
    Archive: MdOutlineArchive,
    Show: FiEye,
    Hide: FiEyeOff,
    Back: FiChevronLeft,
    Left: FiChevronLeft,
    Right: FiChevronRight,
    LeftDouble: FiChevronsLeft,
    RightDouble: FiChevronsRight,
    Grid: FiGrid,
    Save: FiSave,
    Reset: FiRotateCcw,
    Stats: FiBarChart2,
    Calendar: FiCalendar,
    Settings: FiSettings,
    Logout: FiLogOut,
    Award: FiAward,
    Trophy: GiLaurelsTrophy,
    Finance: FaMoneyCheckAlt,
    Search: FiSearch,
    achievements: {
        streakStarter: AiOutlineFire,
        habitFormed: AiOutlineCheckCircle,
        consistencyChampion: IoIosTrophy,
        habitualHero: IoMdFitness,
        habitMaster: MdSchool,
        habitProdigy: GiBrain,
        habitLegend: MdStars,
        steadyEddie: IoIosTimer,
        relentless: MdTimer,
        unstoppable: GiRunningShoe,
        surpassingLimits: MdFlashOn,
        perseverance: FaFighterJet,
        comebackKid: AiOutlineArrowLeft,
    },
    transactionTypes: {
        transfer: BiTransfer,
        income: BiArrowToBottom,
        expense: BiArrowToTop,
    },

    accountTypes: {
        cash: IoCashOutline,
        card: IoCardOutline,
        deposit: RiBankLine,
        loan: BsFillPiggyBankFill,
    },
    expenseIcons: {
        groceries: ShoppingBasket,
        dining: Utensils,
        home: Home,
        utilities: Droplet,
        receipt: Receipt,
        bills: CreditCard,
        taxes: Percent,
        transportation: Car,
        entertainment: Video,
        healthcare: Ambulance,
        education: Book,
        clothing: Shirt,
        insurance: ShieldCheck,
        gifts: Gift,
        electronics: Smartphone,
        travel: Plane,
        pets: PawPrint,
        car: Car,
        subscriptions: Podcast,
        beauty: Sun,
        hobbies: Star,
        charity: Heart,
        repair: Hammer,
        investments: TrendingUp,
        loan: CreditCard,
        childcare: Baby,
        party: CupSoda,
        dental: Smile,
        shopping: ShoppingCart,
        memberships: Tag,
        internet: Wifi,
        phone: Phone,
        sport: Dumbbell,
    },
    incomeIcons: {
        salary: DollarSign,
        freelance: Monitor,
        investments: TrendingUp,
        rental: Home,
        bonus: Star,
        sales: ShoppingCart,
        gifts: Gift,
        refund: CornerDownRight,
    },
};

// TODO: write proxy for icons
// const Icons: {[key: string]: typeof Icon} = new Proxy(IconNames, {
//     get(target, name) {
//         return <Icon as={target[name]} />;
//     },
// });

export default Icons;
