import {
    AiOutlineArrowLeft,
    AiOutlineCheckCircle,
    AiOutlineFire,
    FaFighterJet,
    FiAward,
    FiBarChart2,
    FiCalendar,
    FiLogOut,
    FiSettings,
    GiBrain,
    GiLaurelsTrophy,
    GiRunningShoe,
    IoIosTimer,
    IoIosTrophy,
    IoMdFitness,
    MdFlashOn,
    MdOutlineArchive,
    MdSchool,
    MdStars,
    MdTimer,
} from 'react-icons/all';
import {
    FiArrowRight,
    FiCheck,
    FiChevronLeft,
    FiChevronRight,
    FiChevronsDown,
    FiChevronsLeft,
    FiChevronsRight,
    FiChevronsUp,
    FiEdit3,
    FiEye,
    FiEyeOff,
    FiGrid,
    FiHome,
    FiInbox,
    FiMenu,
    FiPieChart,
    FiPlus,
    FiRotateCcw,
    FiSave,
    FiTrash,
    FiTrash2,
} from 'react-icons/fi';
import { HiFire } from 'react-icons/hi';
import { IoIosNotificationsOutline } from 'react-icons/io';
import { RxCross2 } from 'react-icons/rx';

const Icons = {
    Inbox: FiInbox,
    Complete: FiCheck,
    Cross: RxCross2,
    ArrowTop: FiChevronsUp,
    ArrowBottom: FiChevronsDown,
    ArrowRight: FiArrowRight,
    Streak: HiFire,
    Dashboard: FiHome,
    Menu: FiMenu,
    Notifications: IoIosNotificationsOutline,
    Chart: FiPieChart,
    Add: FiPlus,
    Edit: FiEdit3,
    Delete: FiTrash,
    TrashBin: FiTrash2,
    Archive: MdOutlineArchive,
    Show: FiEye,
    Hide: FiEyeOff,
    Back: FiChevronLeft,
    Left: FiChevronLeft,
    Right: FiChevronRight,
    LeftDouble: FiChevronsLeft,
    RightDouble: FiChevronsRight,
    Grid: FiGrid,
    Save: FiSave,
    Reset: FiRotateCcw,
    Stats: FiBarChart2,
    Calendar: FiCalendar,
    Settings: FiSettings,
    Logout: FiLogOut,
    Award: FiAward,
    Trophy: GiLaurelsTrophy,
    achievements: {
        streakStarter: AiOutlineFire,
        habitFormed: AiOutlineCheckCircle,
        consistencyChampion: IoIosTrophy,
        habitualHero: IoMdFitness,
        habitMaster: MdSchool,
        habitProdigy: GiBrain,
        habitLegend: MdStars,
        steadyEddie: IoIosTimer,
        relentless: MdTimer,
        unstoppable: GiRunningShoe,
        surpassingLimits: MdFlashOn,
        perseverance: FaFighterJet,
        comebackKid: AiOutlineArrowLeft,
    },
};

// TODO: write proxy for icons
// const Icons: {[key: string]: typeof Icon} = new Proxy(IconNames, {
//     get(target, name) {
//         return <Icon as={target[name]} />;
//     },
// });

export default Icons;
